Controllers/CommissionerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Web.Configuration;

using System.IO;
using System.Xml;
using System.Xml.Serialization;

using log4net;
using log4net.Config;

using Mail_WebArchiveView.Models;
using PagedList;
using Microsoft.Exchange.WebServices.Data;


namespace Mail_WebArchiveView.Controllers

{
    public class CommissionerController : Controller
    {
        static readonly ILog logger = LogManager.GetLogger(typeof(CommissionerController));

        public ActionResult Index(int? page)
        {

            XmlSerializer xmlser = new XmlSerializer(typeof(xCommissioners));
            TextReader srdr = new StreamReader(Server.MapPath(Parameters.CommissionersXml));
            object obj = xmlser.Deserialize(srdr);
            xCommissioners Comms = (xCommissioners)obj;
            srdr.Close();

            return View(Comms.Commissioners);
            
        }

        public ActionResult Index2(int? page)
        {

            int pageNumber = (page ?? 1);
            List<Contact> CComms = GetComms();
            //return View(CComms.ToPagedList<Contact>(pageNumber, pageSize));
            return View(CComms);
        }

        public static List<Contact> GetComms()
        {
            ExchangeService service = Connection.ConnectEWS();
            ExpandGroupResults DG = service.ExpandGroup(ConfigurationManager.AppSettings["JournalDG"]);
            IEnumerable<EmailAddress> Members = DG.Members as IEnumerable<EmailAddress>;
            var Comms = new List<EmailAddress>();
            var CComms = new List<Contact>();

            //foreach (string s in Parameters.ArchiveExcludes)
            //{
            //    logger.Debug("Exclude: " + s);
            //}

            if (Parameters.ArchiveExcludes.Count() > 0)
            {
                
                foreach (EmailAddress i in Members)
                {
                    if (!(Parameters.ArchiveExcludes).Any(i.Address.Contains))
                    {
                        Comms.Add(i);

                        NameResolutionCollection coll = service.ResolveName(i.Name,
                                    ResolveNameSearchLocation.ContactsThenDirectory,
                                    true);

                        foreach (NameResolution res in coll)
                        {
                            Contact cont = res.Contact;
                            if (cont != null)
                            {
                                CComms.Add(cont);
                            }
                        }

                    }
                }
            }
            //Add explicit inclusions:
            if (Parameters.ArchiveInclude.Count > 0)
            {
                foreach(Contact i in Parameters.ArchiveInclude)
                {
                    if (i != null)
                    {
                        //logger.Debug("Include: " + i.DisplayName + " (" + i.JobTitle + ") " + i.EmailAddresses[EmailAddressKey.EmailAddress1].Address);
                        CComms.Add(i);
                    }
                }
            }

            return CComms;
        }

        public ActionResult CommissionerList()
        {
            //List<Contact> l = CommissionerController.GetComms();
            //List<EmailAddress> commList = new List<EmailAddress>();

            //foreach (var item in l)
            //{
            //    List<string> eads = new List<string>();


            //    EmailAddress t = new EmailAddress();
            //    t.Name = item.DisplayName;
            //    t.Id = item.JobTitle;
            //    if (item.EmailAddresses != null)
            //    {

            //        if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress1))
            //        {
            //            eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress1].Address);
            //        }

            //        if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress2))
            //        {
            //            eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress2].Address);
            //        }

            //        if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress3))
            //        {
            //            eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress3].Address);
            //        }
            //    }

            //    foreach (string s in eads)
            //    {
            //        if (s.StartsWith("SMTP:", StringComparison.CurrentCulture))
            //        {
            //            t.Address = (s.Split(':')[1]);
            //        }

            //    }

            //    commList.Add(t);
            //}

            //var newlist = commList.ToList();

            XmlSerializer xmlser = new XmlSerializer(typeof(xCommissioners));
            TextReader srdr = new StreamReader(Server.MapPath(Parameters.CommissionersXml));
            object obj = xmlser.Deserialize(srdr);
            xCommissioners Comms = (xCommissioners)obj;
            srdr.Close();

            return PartialView("_CommissionerList", Comms.Commissioners);

            //return PartialView("_CommissionerList", newlist);
        }
    }


}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Commissioner Mail Archive - @ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

        @Scripts.Render("~/bundles/jquery")
        <script type="text/javascript" charset="utf-8" src="//cdnjs.cloudflare.com/ajax/libs/json3/3.3.1/json3.min.js"></script>
        <!--<script type="text/javascript" charset="utf-8" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>-->
  
        @RenderSection("scripts", required: false) 
         
        <!-- Development by J.R. Morgan (C) 2014 -->
        <!-- LiveAverage.com - liveaverage@gmail.com -->

       
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <a class="logo" href="@Url.Action("Index", "Home")"><img class="logo" src="~/Content/Logo.png" /></a>
                    
                </div>
                <div class="float-right">
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Browse", "Index", "Commissioner")</li>
                            <li>@Html.ActionLink("Search", "Index", "Search")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - City of Gainesville, Florida. All rights reserved.</p>
                </div>
            </div>
        </footer>      
        
    </body>
</html>