Controllers/ArchivesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Security.Cryptography;
using System.Web.Script.Serialization;
using System.Text;
using System.Diagnostics;

using log4net;
using log4net.Config;

using PagedList;
using EWS = Microsoft.Exchange.WebServices;
using Microsoft.Exchange.WebServices.Data;
using Mail_WebArchiveView.Models;

namespace Mail_WebArchiveView.Controllers
{
    public class ArchivesController : Controller
    {
        static readonly ILog logger = LogManager.GetLogger(typeof(ArchivesController));

        public ActionResult Index(int? page, string email, string name)
        {
            ExchangeService service = Connection.ConnectEWS();

            FolderView fv = new FolderView(50);
            SearchFilter folderSearch = new SearchFilter.ContainsSubstring(FolderSchema.DisplayName, email);
            var findFoldersResults = service.FindFolders(WellKnownFolderName.Inbox, folderSearch, fv);
            Folder targetFolder = new Folder(service);
            
            foreach (Folder folder in findFoldersResults)
            {
                if (folder.DisplayName.ToLower() == email.ToLower())
                {
                    targetFolder = folder;
                }
            }
            //Define ViewBag.email:
            ViewBag.email = email;
            ViewBag.emailnq = email.Split('@')[0];
            ViewBag.name = name;

            //Create empty list for all mailbox messages:
            var listing = new List<EmailMessage>();
           
            //Create ItemView with correct pagesize and offset:
            ItemView view = new ItemView(int.MaxValue, Connection.ExOffset, OffsetBasePoint.Beginning);

            view.PropertySet = new PropertySet(BasePropertySet.FirstClassProperties,
                EmailMessageSchema.Subject,
                EmailMessageSchema.DateTimeReceived,
                EmailMessageSchema.From
                );

            view.OrderBy.Add(ItemSchema.DateTimeReceived, SortDirection.Descending);

            FindItemsResults<Item> findResults = service.FindItems(targetFolder.Id, view);

            //bool MoreItems = true;

            //while(MoreItems)
            //{
            foreach (EmailMessage it in findResults.Items)
            {
                listing.Add(it);
            }
            //}
            int pageSize = Connection.ExPageSize;
            int pageNumber = (page ?? 1);
            //return View(listing.ToPagedList<EmailMessage>(pageNumber, pageSize));
            return View(listing.ToList<EmailMessage>());
        }

        public ActionResult Browse(string id, string name)
        {
            ViewBag.name = name;
            ViewBag.id = id;

            return View();
        }

        [HttpPost]
        public ActionResult Result(Search sc)
        {
            Session["search"] = sc;

            return View();
        }

        public ActionResult AjaxSearch(jQueryDataTableParamModel param)
        {
            ExchangeService service = Connection.ConnectEWS();
            FindItemsResults<Item> fMsgs;
            FindItemsResults<Item> aMsgs;
            List<EmailMessage> dMsgs = new List<EmailMessage>();

            Folder gsf = GetGlobalFolder(service);

            Search sc = null;

            #region Debug for Search Object:
            //if (sc != null)
            //{
            //    logger.Debug("Hit Ajax Search with Search criteria -- " + sc.subject + sc.to + sc.from + sc.datefrom + sc.dateto);

            //    if (sc.comms != null && sc.comms.Count() > 0)
            //    {
            //        foreach (string s in sc.comms)
            //        {
            //            logger.Debug("Search Commissioner: " + s);
            //        }
            //    }
            //}
            //else
            //{
            //    logger.Debug("AjaxSearch detected NULL SearchSession");
            //}
            #endregion

            string dateFilter;
            string fromFilter;
            string subjectFilter;
            string email;
            int totaldisplay;

            //Try getting the Datatables FILTER parameters or set to null. They're processed/tested later:
            try
            {
                dateFilter = Convert.ToString(Request["sSearch_0"]);
                fromFilter = Convert.ToString(Request["sSearch_1"]);
                subjectFilter = Convert.ToString(Request["sSearch_2"]);
                email = Convert.ToString(Request["email"]);
            }
            catch (Exception e)
            {
                dateFilter = null;
                fromFilter = null;
                subjectFilter = null;
                email = null;
                logger.Debug(e.Message);
            }


            if (!string.IsNullOrWhiteSpace(email))
            {
                //logger.Debug("Received email in querystring: " + email);
            }

            //logger.Debug("sSearch Params -- " + dateFilter + fromFilter + subjectFilter);

            if (sc != null)
            {
                //logger.Debug("Search form criteria -- " + sc.dateto + sc.datefrom);
              
                if ((!string.IsNullOrWhiteSpace(dateFilter) && !dateFilter.Equals("~")) || !string.IsNullOrWhiteSpace(fromFilter) || !string.IsNullOrWhiteSpace(subjectFilter))
                {
                    fMsgs = GetCMessages(service, gsf, sc.comms, param.iDisplayStart, param.iDisplayLength, 
                        sc.datefrom, sc.dateto, sc.to, sc.from, sc.subject, sc.bodytext, 
                        dateFilter, fromFilter, subjectFilter);
                    foreach (EmailMessage i in fMsgs)
                    {
                        dMsgs.Add(i);
                    }
                    totaldisplay = fMsgs.TotalCount;
                }
                else
                {
                    fMsgs = GetCMessages(service, gsf, sc.comms, param.iDisplayStart, param.iDisplayLength, 
                        sc.datefrom, sc.dateto, sc.to, sc.from, sc.subject, sc.bodytext, 
                        dateFilter, fromFilter, subjectFilter);
                    foreach (EmailMessage i in fMsgs)
                    {
                        dMsgs.Add(i);
                    }
                    totaldisplay = fMsgs.TotalCount;
                }

            }
            else if (!string.IsNullOrWhiteSpace(email))
            {
                logger.Debug("No session search detected. Browsing for: " + email);
                gsf = GetSourceFolder(service, email);

                if ((!string.IsNullOrWhiteSpace(dateFilter) && !dateFilter.Equals("~")) || !string.IsNullOrWhiteSpace(fromFilter) || !string.IsNullOrWhiteSpace(subjectFilter))
                {
                    string[] caemail = new string[] { email };

                    aMsgs = GetCMessages(service, gsf, caemail, param.iDisplayStart, param.iDisplayLength, null, null, null, null, null, null, dateFilter, fromFilter, subjectFilter);
                    foreach (EmailMessage i in aMsgs)
                    {
                        dMsgs.Add(i);
                    }
                    totaldisplay = aMsgs.TotalCount;
                }
                else
                {
                    logger.Debug("No filter params detected. Browsing for: " + email);

                    aMsgs = GetCMessages(service, gsf, param.iDisplayStart, param.iDisplayLength);

                    

                    foreach (EmailMessage i in aMsgs)
                    {
                        dMsgs.Add(i);
                    }
                    totaldisplay = aMsgs.TotalCount;
                    logger.Debug("Found messages for " + email + " : " + aMsgs.TotalCount + ". dMsgs count: " + dMsgs.Count);
                }
            }
            else
            {
                if ((!string.IsNullOrWhiteSpace(dateFilter) && !dateFilter.Equals("~")) || !string.IsNullOrWhiteSpace(fromFilter) || !string.IsNullOrWhiteSpace(subjectFilter))
                {
                    string[] c = {};
                    string s = "";
                    fMsgs = GetCMessages(service, gsf, c, param.iDisplayStart, param.iDisplayLength,
                        s, s, s, s, s, s,
                        dateFilter, fromFilter, subjectFilter);
                    foreach (EmailMessage i in fMsgs)
                    {
                        dMsgs.Add(i);
                    }
                    totaldisplay = fMsgs.TotalCount;
                }
                else
                {
                    aMsgs = GetCMessages(service, gsf, param.iDisplayStart, param.iDisplayLength);
                    foreach (EmailMessage i in aMsgs)
                    {
                        dMsgs.Add(i);
                    }
                    totaldisplay = aMsgs.TotalCount;
                }
            }

            
            var result = dMsgs.Select(x => new[] { x.DateTimeReceived.ToString(), x.From.Name, x.Subject, HttpUtility.UrlEncode(x.Id.ToString()), HttpUtility.UrlEncode(x.Id.ToString()) });
            
            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = gsf.TotalCount,
                iTotalDisplayRecords = totaldisplay,
                aaData = result 
            },
            JsonRequestBehavior.AllowGet);
        }

        public ActionResult AjaxSearchResults(jQueryDataTableParamModel param)
        {
            ExchangeService service = Connection.ConnectEWS();
            FindItemsResults<Item> fMsgs;
            FindItemsResults<Item> aMsgs;
            List<EmailMessage> dMsgs = new List<EmailMessage>();

            Folder gsf = GetGlobalFolder(service);

            Search sc = Session["search"] as Search;

            //Search sc = TempData["search"] as Search;

            if (sc != null)
            {

Views/Archives/AJ.cshtml
@using System.Web.Mvc.Html;
@using System.Web.UI;
@using System.Web.Script.Serialization;
@*@model IEnumerable<Microsoft.Exchange.WebServices.Data.EmailMessage>*@

@model Mail_WebArchiveView.Models.Search

@{
    ViewBag.Title = "Message Archive " + ViewBag.name;
}

@section scripts{

<script type="text/javascript" charset="utf-8" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script type="text/javascript" charset="utf-8" src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script type="text/javascript" charset="utf-8" src="//cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf-8" src="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
<script type="text/javascript" charset="utf-8" src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script type="text/javascript" charset="utf-8" src="@Url.Content("~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.columnFilter.js")"></script>

<link href="@Url.Content("~/Content/Site.css")" rel ="stylesheet" /> 
<link href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.3/css/base/jquery.ui.all.css" rel="stylesheet" />
<link href="//cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/css/demo_table_jui.css" rel="stylesheet" />
<link href="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" rel="stylesheet" />

<script type="text/javascript">
    
    $(document).ready(function () {
        $.datepicker.regional[""].dateFormat = 'm/d/yy';
        $.datepicker.setDefaults($.datepicker.regional['']);
        var oMsgIndex = $('#Messages').dataTable({
            "bJQueryUI": true,
            "bServerSide": true,
            "oLanguage": {
                "sProcessing": "Processing <br><img src='@Url.Content("~/Content/ajax-loader.gif")'>"
            },
            "bProcessing": true,
            "sAjaxSource": '@Url.Action("AjaxSearch", "Archives")',
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                /* Add some extra data to the sender */
                aoData.push(
                    { "name": "email", "value": "@Url.RequestContext.RouteData.Values["id"]" },
                    { "name": "query", "value": "@Html.Raw(Json.Encode(Model))" }
                    );
                $.getJSON( sSource, aoData, function (json) { 
                    /* Do whatever additional processing you want on the callback, then tell DataTables */
                    fnCallback(json)
                } ); },
            //Default sort by date descending:
            "aaSorting": [[0, "desc"]],
            // Disable sorting on the last column:
            "aoColumnDefs": [
                {
                    'aTargets': [0],
                    'sType': "date",
                    'sTitle': "Date/Time Received",
                    'bSortable': false
                },
                {
                    'aTargets': [1],
                    'sTitle': "From",
                    'bSortable': false
                },
                {
                    'aTargets': [2],
                    'sTitle': "Subject",
                    'bSortable': false
                },
                {
                    'sTitle': "View",
                    'mRender': function (data, type, row) {
                        return '<a class="vMsg fancybox fancybox.iframe" rel="fb" href="@Url.Action("Index", "Message")?mid=' + data + '&preview=true">Preview</a>' +
                            '<a href="@Url.Action("Index", "Message")?mid=' + data + '&preview=false">View</a>';
@*                        return '<a class="vMsg fancybox fancybox.iframe" rel="fb" href="@Url.Action("Index", "Message")?mid=' + data + '&email=' + @ViewBag.email + '&name=' + @ViewBag.name + '&preview=true">Preview</a>' +
                            '<a href="@Url.Action("Index", "Message")?mid=' + data + '&email=' + @ViewBag.email + '&name=' + @ViewBag.name + '&preview=false">View</a>';*@
                    },
                    'aTargets': [3],
                    'bSortable': false
                },
                {
                    'sTitle': 'Export <input type="checkbox" class="csel2" id="checkall">',
                    'aTargets': [4],
                    'sClass': "export",
                    'mRender': function (data, type, row) {
                        return '<input type="checkbox" class="csel" name="msga" value="' + data + '">'
                    },
                    'bSortable': false
                }
            ],

            "sPaginationType": "full_numbers",
            "bLengthChange": false,
            "bStateSave": true,
            "iDisplayLength": 20

        })
            .columnFilter({
                sPlaceHolder: "head:before",
                aoColumns: [{ type: "date-range" },
				            { type: "text" },
                            { type: "text" },
                            null,
                            null
                ]
            });

        $('#checkall').click(function () {
            $('input', oMsgIndex.fnGetNodes()).attr('checked', this.checked);
        });

        //$('#export').submit(function () {
        //    var sData = oMsgIndex.$('input').serialize();
        //    alert("The following data would have been submitted to the server: \n\n" + sData);
        //    return false;
        //});

        $(".vMsg[rel=fb]").fancybox({
            fitToView: false,
            width: '85%',
            height: '85%',
            autoSize: false,
            closeClick: false,
            openEffect: 'elastic',
            closeEffect: 'elastic',
            showNavArrows: true,
            margin: [20, 60, 20, 60]
        });

        //Handle bulk zip export click:
        $("#gete").click(function () {
            var values = $('input[type="checkbox"].csel:checked').map(function() {
                return $(this).val();
            }).toArray();
            $('#gzip').submit();
        });

        //Hanlde form submit via jquery:
        $("#gzip").on("submit", function (event) {
            event.preventDefault();

            //Show datatables processing:
            $("#Messages_processing").show();
            var url = $(this).attr("action");
            var formData = $(this).serialize();
            $.ajax({
                url: url,
                type: "POST",
                data: JSON.stringify({ msga: values }),
                contentType: 'application/json',
                success: function (result) {

                },
                error: function (err, result) {
                }
            })
        });

    });

</script>
}

<h2>Search Results: @ViewBag.name</h2>
<div id="DivResult"></div>
<div>
@using (Html.BeginForm("GetMessageZip", "Message", FormMethod.Post, new { encType = "multipart/form-data", id="gzip", name = "gzip" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)



<button id="gete" class="minimal" type="submit" style="float:right;margin-bottom:10px">Export Selected (.zip)</button>
<table id="Messages" style="width:100%;margin-top:15px">
    <thead>
        <tr style="border-bottom: 1px solid black;">
        <th style="width:200px;">Date Received</th>
        <th>Filter: From</th>
        <th>Filter: Subject</th>
        <th></th>
        <th></th>
        </tr>
        
        <tr>
        <th style="width:200px;">Date Received</th>
        <th>From</th>
        <th>Subject</th>
        <th></th>
        <th><input type="checkbox" class="csel" name="checkall"></th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

</div>

Views/Archives/AJpost.cshtml
@using System.Web.Mvc.Html;
@model IEnumerable<Microsoft.Exchange.WebServices.Data.EmailMessage>

@*@model Mail_WebArchiveView.Models.Search*@
@{ Layout = null;}

@{
    ViewBag.Title = "Message Archive " + ViewBag.name;
}

@section scripts{

<script type="text/javascript" charset="utf-8" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script type="text/javascript" charset="utf-8" src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script type="text/javascript" charset="utf-8" src="//cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf-8" src="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
<script type="text/javascript" charset="utf-8" src="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script type="text/javascript" charset="utf-8" src="@Url.Content("~/Scripts/DataTables-1.9.4/media/js/jquery.dataTables.columnFilter.js")"></script>

<link href="//cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.3/css/base/jquery.ui.all.css" rel="stylesheet" />
<link href="//cdnjs.cloudflare.com/ajax/libs/datatables/1.9.4/css/demo_table_jui.css" rel="stylesheet" />
<link href="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" rel="stylesheet" />


@*<style type="text/css">
.dataTables_filter {
     display: none;
}

.dataTables_paginate{
    padding-top: 20px;
}

.dataTable th {
    padding-bottom: 15px;
}

tr.odd {
    background-color: #A9D0F5;
}

tr.odd td.sorting_1 {
    background-color: #BFDBF6;
}

tr.even td.sorting_1 {
    background-color: #E1EEFF;
}

.fancybox-nav span {
 visibility: visible;
}

.fancybox-close {
	position: absolute;
	top: -18px;
	right: -18px;
	width: 36px;
	height: 36px;
	cursor: pointer;
	z-index: 8040;
	background-color: transparent;
}

a.fancybox-item:hover, img.fancybox-item:hover {
    position: absolute;
    top: -18px;
    right: -18px;
    width: 36px;
    height: 36px;
    cursor: pointer;
    z-index: 8040;
    background-color: transparent;
}

a.fancybox-prev:hover, img.fancybox-prev:hover {
	background-color: transparent;
}

a.fancybox-next:hover, img.fancybox-next:hover {
	background-color: transparent;
}

.fancybox-nav {
    width: 10%;
}

.dataTables_processing {
    background-color: white;
}

</style>*@

<script type="text/javascript">
    
    $(document).ready(function () {
        $.datepicker.regional[""].dateFormat = 'm/d/yy';
        $.datepicker.setDefaults($.datepicker.regional['']);
        var oMsgIndex = $('#Messages').dataTable({
            "bJQueryUI": true,
            "bServerSide": true,
            "oLanguage": {
                "sProcessing": 'Processing <img src="@Url.Content("~/Content/ajax-loader.gif")>'
            },
            "bProcessing": true,
            "sAjaxSource": '@Url.Action("AjaxSearch", "Archives")',
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                /* Add some extra data to the sender */
                aoData.push(
                    { "name": "email", "value": "@Url.RequestContext.RouteData.Values["id"]" }
                    );
                $.getJSON( sSource, aoData, function (json) { 
                    /* Do whatever additional processing you want on the callback, then tell DataTables */
                    fnCallback(json)
                } ); },
            //Default sort by date descending:
            "aaSorting": [[0, "desc"]],
            // Disable sorting on the last column:
            "aoColumnDefs": [
                {
                    'aTargets': [0],
                    'sType': "date",
                    'sTitle': "Date/Time Received",
                    'bSortable': false
                },
                {
                    'aTargets': [1],
                    'sTitle': "From",
                    'bSortable': false
                },
                {
                    'aTargets': [2],
                    'sTitle': "Subject",
                    'bSortable': false
                },
                {
                    'sTitle': "View",
                    'mRender': function (data, type, row) {
                        return '<a class="vMsg fancybox fancybox.iframe" rel="fb" href="@Url.Action("Index", "Message")?mid=' + data + '&preview=true">Preview</a>' +
                            '<a href="@Url.Action("Index", "Message")?mid=' + data + '&preview=false">View</a>';
@*                        return '<a class="vMsg fancybox fancybox.iframe" rel="fb" href="@Url.Action("Index", "Message")?mid=' + data + '&email=' + @ViewBag.email + '&name=' + @ViewBag.name + '&preview=true">Preview</a>' +
                            '<a href="@Url.Action("Index", "Message")?mid=' + data + '&email=' + @ViewBag.email + '&name=' + @ViewBag.name + '&preview=false">View</a>';*@
                    },
                        //'<a href="' + data + '">Preview</a>'; },
                    'aTargets': [3],
                    'bSortable': false
                }
            ],

            "sPaginationType": "full_numbers",
            "bLengthChange": false,
            "bStateSave": true,
            "iDisplayLength": 10

        })
            .columnFilter({
                sPlaceHolder: "head:before",
                aoColumns: [{ type: "date-range" },
				            { type: "text" },
                            { type: "text" },
                            null
                ]
            });

        $("#Refresh").click(function (e) {
            oMsgIndex.fnDraw();
        });

        /* Clears the filtering inputs and selects */
        $.fn.clearForm = function () {
            return this.each(function () {
                var type = this.type, tag = this.tagName.toLowerCase();
                if (tag == 'form')
                    return $(':input', this).clearForm();
                if (type == 'text' || type == 'password' || tag == 'textarea')
                    this.value = '';
                else if (type == 'checkbox' || type == 'radio')
                    this.checked = false;
                else if (tag == 'select')
                    this.selectedIndex = -1;
            });
        };

        /* Removes filters from the table data and restores all data */
        $.fn.dataTableExt.oApi.fnFilterClear = function ( oSettings )
        {
            /* Remove global filter */
            oSettings.oPreviousSearch.sSearch = "";

            /* Remove the text of the global filter in the input boxes */
            if ( typeof oSettings.aanFeatures.f != 'undefined' )
            {
                var n = oSettings.aanFeatures.f;
                for ( var i=0, iLen=n.length ; i<iLen ; i++ )
                {
                    $('input', n[i]).val( '' );
                }
            }
            /* Remove the search text for the column filters - NOTE - if you have input boxes for these
            * filters, these will need to be reset
            */
            for (var i = 0, iLen = oSettings.aoPreSearchCols.length ; i < iLen ; i++) {
                oSettings.aoPreSearchCols[i].sSearch = "";
            }

            /* Redraw */
            oSettings.oApi._fnReDraw(oSettings);
        }

            $("button").click(function () {
                $(':input').clearForm();
                oMsgIndex.fnFilterClear();
                oMsgIndex.fnDraw();
            });


        //$(".fancybox")
        //    .attr('rel', 'fb')
        //    .fancybox({
        //        width: '80%',
        //        height: '80%',
        //        padding: 0,
        //        margin: [20, 60, 20, 60], // Increase left/right margin
        //        closeClick: false,
        //        openEffect: 'elastic',
        //        closeEffect: 'elastic',

        //    });
        $(".vMsg[rel=fb]").fancybox({
            fitToView: false,
            width: '85%',
            height: '85%',
            autoSize: false,
            closeClick: false,
            openEffect: 'elastic',
            closeEffect: 'elastic',
            showNavArrows: true,
            margin: [20, 60, 20, 60]
        });
    });

</script>
}

<h2>Message Index: @ViewBag.name</h2>
<div>
<button id="Refresh" style="float:right;" type="button">Refresh</button>

<table id="Messages" style="width:100%;margin-top:15px">
    <thead>
        <tr style="border-bottom: 1px solid black;">
        <th style="width:200px;">Date Received</th>
        <th>Filter: From</th>
        <th>Filter: Subject</th>
        <th></th>
        </tr>
        
        <tr>
        <th style="width:200px;">Date Received</th>
        <th>From</th>
        <th>Subject</th>
        <th></th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
</div>

Views/Archives/AS3.cshtml
@model Mail_WebArchiveView.Models.Search

@{ Layout = null;}