Models/Commissioner.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.Exchange.WebServices.Data;
using System.Xml;
using System.Xml.Serialization;


namespace Mail_WebArchiveView.Models
{
    public class Commissioner
    {
        public string[] SelectedIds { get; set; }
        public List<Contact> Contacts { get; set; }
    }
    [XmlRoot("Commissioner")]
    public class xCommissioner
    {
        public string Name { get; set; }
        public string Title { get; set; }
        public string Mail { get; set; }
        public string CurrentCommissioner { get; set; }
    }

    [XmlRoot("ArrayOfCommissioner")]
    public class xCommissioners
    {
        [XmlElement("Commissioner")]
        public List<xCommissioner> Commissioners { get; set; }
    }
}   

Controllers/ArchiveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Security.Cryptography;
using System.Text;

using log4net;
using log4net.Config;

using PagedList;
using EWS = Microsoft.Exchange.WebServices;
using Microsoft.Exchange.WebServices.Data;
using Mail_WebArchiveView.Models;

//Needed for JSON output to jQuery:
using System.Web.Script.Serialization;


namespace Mail_WebArchiveView.Controllers
{
    public class ArchiveController : Controller
    {

        public ActionResult Index(int? page, string email, string name)
        {
            ExchangeService service = Connection.ConnectEWS();

            FolderView fv = new FolderView(50);
            SearchFilter folderSearch = new SearchFilter.ContainsSubstring(FolderSchema.DisplayName, email.ToLower());
            var findFoldersResults = service.FindFolders(WellKnownFolderName.Inbox, folderSearch, fv);
            Folder targetFolder = null;

            foreach (Folder folder in findFoldersResults)
            {
                if (folder.DisplayName.ToLower() == email.ToLower())
                {
                    targetFolder = folder;
                }
            }
            //Define ViewBag.email:
            ViewBag.email = email;
            ViewBag.emailnq = email.Split('@')[0];
            ViewBag.name = name;

            //Create empty list for all mailbox messages:
            var listing = new List<EmailMessage>();

            //Create ItemView with correct pagesize and offset:
            ItemView view = new ItemView(int.MaxValue, Connection.ExOffset, OffsetBasePoint.Beginning);

            view.PropertySet = new PropertySet(BasePropertySet.FirstClassProperties,
                EmailMessageSchema.Subject,
                EmailMessageSchema.DateTimeReceived,
                EmailMessageSchema.From
                );

            view.OrderBy.Add(ItemSchema.DateTimeReceived, SortDirection.Descending);

            FindItemsResults<Item> findResults = service.FindItems(targetFolder.Id, view);

            //bool MoreItems = true;

            //while(MoreItems)
            //{
            foreach (EmailMessage it in findResults.Items)
            {
                listing.Add(it);
            }
            //}
            int pageSize = Connection.ExPageSize;
            int pageNumber = (page ?? 1);
            //return View(listing.ToPagedList<EmailMessage>(pageNumber, pageSize));
            return View(listing.ToList<EmailMessage>());
        }

        public string Welcome(string name, int numTime = 1)
        {
            //return "This is the Welcome action method...";
            return HttpUtility.HtmlEncode("Hello " + name + ", NumTimes is: " + numTime);
        }

        public ActionResult Messages()
        {
            RDOSession Session = new RDOSession();
            Session.Logon();
            RDOExchangeMailboxStore mbStore = (RDOExchangeMailboxStore)Session.Stores.DefaultStore;

            //Evaluate with Drafts folder:
            RDOFolder Inbox = (RDOFolder)Session.GetDefaultFolder(rdoDefaultFolders.olFolderDrafts);

            var listing = new List<Message>();

            foreach (RDOMail item in Inbox.Items)
            {
                var temp = new Message();
                temp.Subject = item.Subject;
                temp.Received = item.ReceivedTime;
                temp.ID = item.EntryID;
                listing.Add(temp);
                temp = null;
            }
            
            GC.Collect();

            return View(listing.ToList<Message>());
        }

        public ActionResult MessageEWS(EmailAddress email)
        {
            ExchangeService service = Connection.ConnectEWS();

            //Create empty list for all mailbox messages:
            var listing = new List<EmailMessage>();

            //Create ItemView with correct pagesize and offset:
            ItemView view = new ItemView(Connection.ExPageSize, Connection.ExOffset, OffsetBasePoint.Beginning);

            view.PropertySet = new PropertySet(BasePropertySet.FirstClassProperties,
                EmailMessageSchema.Subject,
                EmailMessageSchema.DateTimeReceived,
                EmailMessageSchema.From,
                EmailMessageSchema.ToRecipients);

            view.OrderBy.Add(ItemSchema.DateTimeReceived, SortDirection.Descending);

            //string sf = "Body:\"Compensation\"";

            //Define the new PidTagParentDisplay property to use for filtering:
            ExtendedPropertyDefinition def = new ExtendedPropertyDefinition(0x0E05, MapiPropertyType.String);
            SearchFilter searchCriteria = new SearchFilter.IsEqualTo(def, email.Address);
            FindItemsResults<Item> findResults = service.FindItems(WellKnownFolderName.Inbox, searchCriteria, view);

            foreach (EmailMessage it in findResults.Items)
            {
                listing.Add(it);
            }

            return View(listing.ToList<EmailMessage>());
        }

        private static Folder GetSourceFolder(ExchangeService service, EmailAddress email)
        {
            log4net.Config.XmlConfigurator.Configure();
           
            // Use the following search filter to get all mail in the Inbox with the word "extended" in the subject line.
            SearchFilter searchCriteria = new SearchFilter.SearchFilterCollection(LogicalOperator.And,
                //Search for Folder DisplayName that matches mailbox email address:
                new SearchFilter.IsEqualTo(FolderSchema.DisplayName, email.Address));

            // Find the search folder named "MailModder".
            FindFoldersResults findResults = service.FindFolders(
                WellKnownFolderName.Inbox,
                searchCriteria,
                new FolderView(50));
            
            //Return root of inbox by default:
            Folder returnFolder = Folder.Bind(service, WellKnownFolderName.Inbox);
            foreach (Folder searchFolder in findResults.Folders)
            {
                if (searchFolder.DisplayName == email.Address)
                {
                    returnFolder = searchFolder;
                }
            }

            return returnFolder;
        }

        public static bool CertificateValidationCallBack(object sender, System.Security.Cryptography.X509Certificates.X509Certificate certificate, System.Security.Cryptography.X509Certificates.X509Chain chain, System.Net.Security.SslPolicyErrors sslPolicyErrors)
        {
            // If the certificate is a valid, signed certificate, return true.
            if (sslPolicyErrors == System.Net.Security.SslPolicyErrors.None)
            {
                return true;
            }

            // If there are errors in the certificate chain, look at each error to determine the cause.
            if ((sslPolicyErrors & System.Net.Security.SslPolicyErrors.RemoteCertificateChainErrors) != 0)
            {
                if (chain != null && chain.ChainStatus != null)
                {
                    foreach (System.Security.Cryptography.X509Certificates.X509ChainStatus status in chain.ChainStatus)
                    {
                        if ((certificate.Subject == certificate.Issuer) &&
                           (status.Status == System.Security.Cryptography.X509Certificates.X509ChainStatusFlags.UntrustedRoot))
                        {
                            // Self-signed certificates with an untrusted root are valid. 
                            continue;
                        }
                        else
                        {
                            if (status.Status != System.Security.Cryptography.X509Certificates.X509ChainStatusFlags.NoError)
                            {
                                // If there are any other errors in the certificate chain, the certificate is invalid,
                                // so the method returns false.
                                return false;
                            }
                        }
                    }
                }

                // When processing reaches this line, the only errors in the certificate chain are 
                // untrusted root errors for self-signed certificates. These certificates are valid
                // for default Exchange server installations, so return true.
                return true;
            }
            else
            {
                // In all other cases, return false.
                return false;
            }
        }

    }

}

Controllers/CommissionerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Web.Configuration;

using System.IO;
using System.Xml;
using System.Xml.Serialization;

using log4net;
using log4net.Config;

using Mail_WebArchiveView.Models;
using PagedList;
using Microsoft.Exchange.WebServices.Data;


namespace Mail_WebArchiveView.Controllers

{
    public class CommissionerController : Controller
    {
        static readonly ILog logger = LogManager.GetLogger(typeof(CommissionerController));

        public ActionResult Index(int? page)
        {

            XmlSerializer xmlser = new XmlSerializer(typeof(xCommissioners));
            TextReader srdr = new StreamReader(Server.MapPath(Parameters.CommissionersXml));
            object obj = xmlser.Deserialize(srdr);
            xCommissioners Comms = (xCommissioners)obj;
            srdr.Close();

            return View(Comms.Commissioners);
            
        }

        public ActionResult Index2(int? page)
        {

            int pageNumber = (page ?? 1);
            List<Contact> CComms = GetComms();
            //return View(CComms.ToPagedList<Contact>(pageNumber, pageSize));
            return View(CComms);
        }

        public static List<Contact> GetComms()
        {
            ExchangeService service = Connection.ConnectEWS();
            ExpandGroupResults DG = service.ExpandGroup(ConfigurationManager.AppSettings["JournalDG"]);
            IEnumerable<EmailAddress> Members = DG.Members as IEnumerable<EmailAddress>;
            var Comms = new List<EmailAddress>();
            var CComms = new List<Contact>();

            //foreach (string s in Parameters.ArchiveExcludes)
            //{
            //    logger.Debug("Exclude: " + s);
            //}

            if (Parameters.ArchiveExcludes.Count() > 0)
            {
                
                foreach (EmailAddress i in Members)
                {
                    if (!(Parameters.ArchiveExcludes).Any(i.Address.Contains))
                    {
                        Comms.Add(i);

                        NameResolutionCollection coll = service.ResolveName(i.Name,
                                    ResolveNameSearchLocation.ContactsThenDirectory,
                                    true);

                        foreach (NameResolution res in coll)
                        {
                            Contact cont = res.Contact;
                            if (cont != null)
                            {
                                CComms.Add(cont);
                            }
                        }

                    }
                }
            }
            //Add explicit inclusions:
            if (Parameters.ArchiveInclude.Count > 0)
            {
                foreach(Contact i in Parameters.ArchiveInclude)
                {
                    if (i != null)
                    {
                        //logger.Debug("Include: " + i.DisplayName + " (" + i.JobTitle + ") " + i.EmailAddresses[EmailAddressKey.EmailAddress1].Address);
                        CComms.Add(i);
                    }
                }
            }

            return CComms;
        }

        public ActionResult CommissionerList()
        {
            //List<Contact> l = CommissionerController.GetComms();
            //List<EmailAddress> commList = new List<EmailAddress>();

            //foreach (var item in l)
            //{
            //    List<string> eads = new List<string>();


            //    EmailAddress t = new EmailAddress();
            //    t.Name = item.DisplayName;
            //    t.Id = item.JobTitle;
            //    if (item.EmailAddresses != null)
            //    {

            //        if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress1))
            //        {
            //            eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress1].Address);
            //        }

            //        if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress2))
            //        {
            //            eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress2].Address);
            //        }

            //        if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress3))
            //        {
            //            eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress3].Address);
            //        }
            //    }

            //    foreach (string s in eads)
            //    {
            //        if (s.StartsWith("SMTP:", StringComparison.CurrentCulture))
            //        {
            //            t.Address = (s.Split(':')[1]);
            //        }

            //    }

            //    commList.Add(t);
            //}

            //var newlist = commList.ToList();

            XmlSerializer xmlser = new XmlSerializer(typeof(xCommissioners));
            TextReader srdr = new StreamReader(Server.MapPath(Parameters.CommissionersXml));
            object obj = xmlser.Deserialize(srdr);
            xCommissioners Comms = (xCommissioners)obj;
            srdr.Close();

            return PartialView("_CommissionerList", Comms.Commissioners);

            //return PartialView("_CommissionerList", newlist);
        }
    }


}

Views/Commissioner/Index.cshtml
@using System.Web.Mvc.Html;
@using PagedList.Mvc;
@using Microsoft.Exchange.WebServices.Data;
@using Mail_WebArchiveView.Models;
@*@model PagedList.IPagedList<Microsoft.Exchange.WebServices.Data.Contact>*@
@model List<xCommissioner>



<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "City Commission Listing";
}

<h2>Mayor</h2>

<ul class="round">

@foreach (var item in Model.Where(comm => !string.IsNullOrWhiteSpace(comm.Title) && comm.Title.Contains("Mayor")).OrderBy(comm => comm.Name))
{
    string id = null;
    id = (item.Mail).Split('@')[0];
        
    <li>
    @Html.ActionLink(item.Name, "Browse", "Archives", new { id=id, name=item.Name}, null)
    </li>    
    break;   

}
</ul>

<h2>City Commission Listing</h2>

<ul class="round">

@foreach (var item in Model.Where(comm => comm.CurrentCommissioner.Contains("True") && !string.IsNullOrWhiteSpace(comm.Title) && !comm.Title.Contains("Mayor") && !comm.Title.Contains("Term")).OrderBy(comm => comm.Title).ThenBy(comm => comm.Name))
{
    string id = null;
    id = (item.Mail).Split('@')[0];
        
    <li>
    @Html.ActionLink(item.Name + " (" + item.Title + ") ", "Browse", "Archives", new { id=id, name=item.Name}, null)
    </li>       

}
</ul>

@if ((Model.Where(comm => comm.CurrentCommissioner.Contains("False"))).Count() > 0)
{
<h2>Previous Commissioners</h2>
<ul>
@foreach (var item in Model.Where(comm => !string.IsNullOrWhiteSpace(comm.Title) && comm.CurrentCommissioner.Contains("False")).OrderBy(comm => comm.Name))
{
    string id = null;
    id = (item.Mail).Split('@')[0];
    <li>
    @Html.ActionLink(item.Name + " (" + item.Title + ") ", "Browse", "Archives", new { id = id, name=item.Name}, null) 
    </li>       

}
</ul>
}
<br />
@*Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))*@

Views/Commissioner/Index2.cshtml
@using System.Web.Mvc.Html;
@using PagedList.Mvc;
@using Microsoft.Exchange.WebServices.Data;
@using Mail_WebArchiveView.Models;
@*@model PagedList.IPagedList<Microsoft.Exchange.WebServices.Data.Contact>*@
@model List<Microsoft.Exchange.WebServices.Data.Contact>



<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "City Commission Listing";
}

<h2>Mayor</h2>

<ul class="round">

@foreach (var item in Model.Where(comm => !string.IsNullOrWhiteSpace(comm.JobTitle) && comm.JobTitle.Contains("Mayor")).OrderBy(comm => comm.DisplayName))
{    
    List<string> eads = new List<string>();
    string email = null;
    string id = null;
    if(item.JobTitle.Contains("Mayor"))
    {
        if(item.EmailAddresses != null)
        {

            if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress1))
            {
                eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress1].Address);
            }

            if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress2))
            {
                eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress2].Address);
            }

            if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress3))
            {
                eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress3].Address);
            }
        }
        
        foreach (string s in eads)   
        {
            if (s.StartsWith("SMTP:", StringComparison.CurrentCulture))
            {
                email = s.Split(':')[1];
                id = email.Split('@')[0];
            }
                
        }
        
        <li>
        @Html.ActionLink(item.DisplayName, "Browse", "Archives", new { id=id, name=item.DisplayName}, null)
        </li>    
        break;   
    }
}
</ul>

<h2>City Commission Listing</h2>

<ul class="round">

@foreach (var item in Model.Where(comm => !string.IsNullOrWhiteSpace(comm.JobTitle) && !comm.JobTitle.Contains("Mayor") && !comm.JobTitle.Contains("Term")).OrderBy(comm => comm.JobTitle).ThenBy(comm => comm.DisplayName))
{
    List<string> eads = new List<string>();
    string email = null;
    string id = null;
    
        if (item.EmailAddresses != null)
        {

            if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress1))
            {
                eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress1].Address);
            }

            if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress2))
            {
                eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress2].Address);
            }

            if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress3))
            {
                eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress3].Address);
            }
        }

        foreach (string s in eads)
        {
            if (s.StartsWith("SMTP:", StringComparison.CurrentCulture))
            {
                email = s.Split(':')[1];
                id = email.Split('@')[0];
            }

        }  
        <li>
        @Html.ActionLink(item.DisplayName + " (" + item.JobTitle + ") ", "Browse", "Archives", new { id=id, name=item.DisplayName}, null)
        </li>       

}
</ul>

@if((Model.Where(comm => comm.JobTitle.Contains("Term"))).Count() > 0)
{
<h2>Previous Commissioners</h2>
<ul>
@foreach (var item in Model.Where(comm => !string.IsNullOrWhiteSpace(comm.JobTitle) && comm.JobTitle.Contains("Term")).OrderBy(comm => comm.DisplayName))
{
    List<string> eads = new List<string>();
    
    string email = null;
    string id = null;
    
    //if(!item.JobTitle.Contains("Mayor") && !string.IsNullOrWhiteSpace(item.JobTitle))
    //{
        if (item.EmailAddresses != null)
        {

            if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress1))
            {
                eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress1].Address);
            }

            if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress2))
            {
                eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress2].Address);
            }

            if (item.EmailAddresses.Contains(EmailAddressKey.EmailAddress3))
            {
                eads.Add(item.EmailAddresses[EmailAddressKey.EmailAddress3].Address);
            }
        }

        foreach (string s in eads)
        {
            if (s.StartsWith("SMTP:", StringComparison.CurrentCulture))
            {
                email = s.Split(':')[1];
                id = email.Split('@')[0];
            }

        }  
        <li>
        @Html.ActionLink(item.DisplayName + " (" + item.JobTitle + ") ", "Browse", "Archives", new { id = id, name=item.DisplayName}, null) 
        </li>       
    //}
}
</ul>
}
<br />
@*Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))*@

Views/Commissioner/Index3.cshtml
@using System.Web.Mvc.Html;
@using PagedList.Mvc;
@model PagedList.IPagedList<Microsoft.Exchange.WebServices.Data.EmailAddress>



<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "City Commission Listing";
}

<h2>City Commission Listing</h2>

<ul class="round">

@foreach (var item in Model.OrderBy(comm => comm.Name))
{    
    <li>
    @Html.ActionLink(item.Name, "Index", "Archive", new { email = item.Address, name=item.Name}, null)
    </li>       
}

</ul>

<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))

Views/Commissioner/Index_OLD.cshtml
@{
    ViewBag.Title = "Commissioner Listing";
}

<h2>Commissioner Listing</h2>

@model IEnumerable<Mail_WebArchiveView.Models.MailboxC> 

<ul class="round">

@foreach (var item in Model)
{

    <li>
        @Html.DisplayFor(modelItem => item.DisplayName) (@Html.DisplayFor(modelItem => item.uid[1]))
    </li>       
    

}

</ul>

Views/Commissioner/_CommissionerList.cshtml
@using Mail_WebArchiveView.Models;
@model List<xCommissioner>

@{
    Layout = null;
}

<h2>City Commission Listing</h2>

<ul class="round">

@foreach (var item in Model.Where(comm => comm.CurrentCommissioner.Contains("True") && !string.IsNullOrWhiteSpace(comm.Title) && comm.Title.Contains("Mayor")).OrderBy(comm => comm.Title).ThenBy(comm => comm.Name))
{
    string id = null;
    id = (item.Mail).Split('@')[0];
        
    <li>
    @Html.ActionLink(item.Name + " (" + item.Title + ") ", "Browse", "Archives", new { id=id, name=item.Name}, null)
    </li>       

}

@foreach (var item in Model.Where(comm => comm.CurrentCommissioner.Contains("True") && !string.IsNullOrWhiteSpace(comm.Title) && !comm.Title.Contains("Mayor")).OrderBy(comm => comm.Title).ThenBy(comm => comm.Name))
{
    string id = null;
    id = (item.Mail).Split('@')[0];
        
    <li>
    @Html.ActionLink(item.Name + " (" + item.Title + ") ", "Browse", "Archives", new { id=id, name=item.Name}, null)
    </li>       

}
</ul>